name: Feature request
description: Sugerir uma melhoria
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Qual problema isso resolve?
    validations: { required: true }
  - type: textarea
    id: proposal
    attributes:
      label: Proposta
