/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVadeMecumRouteImport } from './routes/_app.vade-mecum'
import { Route as AppRetaFinalRouteImport } from './routes/_app.reta-final'
import { Route as AppQuestoesRouteImport } from './routes/_app.questoes'
import { Route as AppProgressoRouteImport } from './routes/_app.progresso'
import { Route as AppPlanoEstudoRouteImport } from './routes/_app.plano-estudo'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppNoticiasRouteImport } from './routes/_app.noticias'
import { Route as AppMateriasRouteImport } from './routes/_app.materias'
import { Route as AppFlashcardsRouteImport } from './routes/_app.flashcards'
import { Route as AppBlogRouteImport } from './routes/_app.blog'
import { Route as AppBibliotecaRouteImport } from './routes/_app.biblioteca'
import { Route as AppAulasRouteImport } from './routes/_app.aulas'
import { Route as AppAudioaulasRouteImport } from './routes/_app.audioaulas'
import { Route as AppAssistenteRouteImport } from './routes/_app.assistente'
import { Route as AppAppRouteImport } from './routes/_app.app'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppSimuladosIndexRouteImport } from './routes/_app.simulados.index'
import { Route as AppResumosIndexRouteImport } from './routes/_app.resumos.index'
import { Route as AppProvasIndexRouteImport } from './routes/_app.provas.index'
import { Route as AppBibliotecaIndexRouteImport } from './routes/_app.biblioteca.index'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as ApiPublicSeedProvasRouteImport } from './routes/api.public.seed-provas'
import { Route as AppResumosLivroIdRouteImport } from './routes/_app.resumos.$livroId'
import { Route as AppProvasNumeroRouteImport } from './routes/_app.provas.$numero'
import { Route as AppOabSegundaFaseRouteImport } from './routes/_app.oab.segunda-fase'
import { Route as AppOabReforcoRouteImport } from './routes/_app.oab.reforco'
import { Route as AppOabProgressoRouteImport } from './routes/_app.oab.progresso'
import { Route as AppOabPrimeiraFaseRouteImport } from './routes/_app.oab.primeira-fase'
import { Route as AppOabPecaModeloRouteImport } from './routes/_app.oab.peca-modelo'
import { Route as AppOabOQueEstudarRouteImport } from './routes/_app.oab.o-que-estudar'
import { Route as AppOabCronogramaRouteImport } from './routes/_app.oab.cronograma'
import { Route as AppOabCalendarioRouteImport } from './routes/_app.oab.calendario'
import { Route as AppOabCadernoErrosRouteImport } from './routes/_app.oab.caderno-erros'
import { Route as AppNoticiasIdRouteImport } from './routes/_app.noticias.$id'
import { Route as AppMateriasSlugRouteImport } from './routes/_app.materias.$slug'
import { Route as AppBlogSlugRouteImport } from './routes/_app.blog.$slug'
import { Route as AppBibliotecaSlugRouteImport } from './routes/_app.biblioteca.$slug'
import { Route as AppAdminSimuladosRouteImport } from './routes/_app.admin.simulados'
import { Route as AppAdminResumosRouteImport } from './routes/_app.admin.resumos'
import { Route as AppAdminBlogRouteImport } from './routes/_app.admin.blog'
import { Route as AppVadeMecumEstatutosIndexRouteImport } from './routes/_app.vade-mecum.estatutos.index'
import { Route as AppSimuladosSlugIndexRouteImport } from './routes/_app.simulados.$slug.index'
import { Route as AppBibliotecaSlugIndexRouteImport } from './routes/_app.biblioteca.$slug.index'
import { Route as AppVadeMecumEstatutosSlugRouteImport } from './routes/_app.vade-mecum.estatutos.$slug'
import { Route as AppSimuladosSlugPraticarRouteImport } from './routes/_app.simulados.$slug.praticar'
import { Route as AppBibliotecaSlugBookIdRouteImport } from './routes/_app.biblioteca.$slug.$bookId'
import { Route as AppBibliotecaSlugBookIdIndexRouteImport } from './routes/_app.biblioteca.$slug.$bookId.index'
import { Route as AppSimuladosSlugResultadoTentativaIdRouteImport } from './routes/_app.simulados.$slug.resultado.$tentativaId'
import { Route as AppResumosCapituloLivroIdOrdemRouteImport } from './routes/_app.resumos.capitulo.$livroId.$ordem'
import { Route as AppBibliotecaSlugBookIdLerRouteImport } from './routes/_app.biblioteca.$slug.$bookId.ler'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVadeMecumRoute = AppVadeMecumRouteImport.update({
  id: '/vade-mecum',
  path: '/vade-mecum',
  getParentRoute: () => AppRoute,
} as any)
const AppRetaFinalRoute = AppRetaFinalRouteImport.update({
  id: '/reta-final',
  path: '/reta-final',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestoesRoute = AppQuestoesRouteImport.update({
  id: '/questoes',
  path: '/questoes',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressoRoute = AppProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanoEstudoRoute = AppPlanoEstudoRouteImport.update({
  id: '/plano-estudo',
  path: '/plano-estudo',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticiasRoute = AppNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => AppRoute,
} as any)
const AppMateriasRoute = AppMateriasRouteImport.update({
  id: '/materias',
  path: '/materias',
  getParentRoute: () => AppRoute,
} as any)
const AppFlashcardsRoute = AppFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AppRoute,
} as any)
const AppBlogRoute = AppBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRoute,
} as any)
const AppAulasRoute = AppAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AppRoute,
} as any)
const AppAudioaulasRoute = AppAudioaulasRouteImport.update({
  id: '/audioaulas',
  path: '/audioaulas',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistenteRoute = AppAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AppRoute,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSimuladosIndexRoute = AppSimuladosIndexRouteImport.update({
  id: '/simulados/',
  path: '/simulados/',
  getParentRoute: () => AppRoute,
} as any)
const AppResumosIndexRoute = AppResumosIndexRouteImport.update({
  id: '/resumos/',
  path: '/resumos/',
  getParentRoute: () => AppRoute,
} as any)
const AppProvasIndexRoute = AppProvasIndexRouteImport.update({
  id: '/provas/',
  path: '/provas/',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaIndexRoute = AppBibliotecaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBibliotecaRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const ApiPublicSeedProvasRoute = ApiPublicSeedProvasRouteImport.update({
  id: '/api/public/seed-provas',
  path: '/api/public/seed-provas',
  getParentRoute: () => rootRouteImport,
} as any)
const AppResumosLivroIdRoute = AppResumosLivroIdRouteImport.update({
  id: '/resumos/$livroId',
  path: '/resumos/$livroId',
  getParentRoute: () => AppRoute,
} as any)
const AppProvasNumeroRoute = AppProvasNumeroRouteImport.update({
  id: '/provas/$numero',
  path: '/provas/$numero',
  getParentRoute: () => AppRoute,
} as any)
const AppOabSegundaFaseRoute = AppOabSegundaFaseRouteImport.update({
  id: '/oab/segunda-fase',
  path: '/oab/segunda-fase',
  getParentRoute: () => AppRoute,
} as any)
const AppOabReforcoRoute = AppOabReforcoRouteImport.update({
  id: '/oab/reforco',
  path: '/oab/reforco',
  getParentRoute: () => AppRoute,
} as any)
const AppOabProgressoRoute = AppOabProgressoRouteImport.update({
  id: '/oab/progresso',
  path: '/oab/progresso',
  getParentRoute: () => AppRoute,
} as any)
const AppOabPrimeiraFaseRoute = AppOabPrimeiraFaseRouteImport.update({
  id: '/oab/primeira-fase',
  path: '/oab/primeira-fase',
  getParentRoute: () => AppRoute,
} as any)
const AppOabPecaModeloRoute = AppOabPecaModeloRouteImport.update({
  id: '/oab/peca-modelo',
  path: '/oab/peca-modelo',
  getParentRoute: () => AppRoute,
} as any)
const AppOabOQueEstudarRoute = AppOabOQueEstudarRouteImport.update({
  id: '/oab/o-que-estudar',
  path: '/oab/o-que-estudar',
  getParentRoute: () => AppRoute,
} as any)
const AppOabCronogramaRoute = AppOabCronogramaRouteImport.update({
  id: '/oab/cronograma',
  path: '/oab/cronograma',
  getParentRoute: () => AppRoute,
} as any)
const AppOabCalendarioRoute = AppOabCalendarioRouteImport.update({
  id: '/oab/calendario',
  path: '/oab/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppOabCadernoErrosRoute = AppOabCadernoErrosRouteImport.update({
  id: '/oab/caderno-erros',
  path: '/oab/caderno-erros',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticiasIdRoute = AppNoticiasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppNoticiasRoute,
} as any)
const AppMateriasSlugRoute = AppMateriasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppMateriasRoute,
} as any)
const AppBlogSlugRoute = AppBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppBlogRoute,
} as any)
const AppBibliotecaSlugRoute = AppBibliotecaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppBibliotecaRoute,
} as any)
const AppAdminSimuladosRoute = AppAdminSimuladosRouteImport.update({
  id: '/simulados',
  path: '/simulados',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminResumosRoute = AppAdminResumosRouteImport.update({
  id: '/resumos',
  path: '/resumos',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBlogRoute = AppAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppVadeMecumEstatutosIndexRoute =
  AppVadeMecumEstatutosIndexRouteImport.update({
    id: '/estatutos/',
    path: '/estatutos/',
    getParentRoute: () => AppVadeMecumRoute,
  } as any)
const AppSimuladosSlugIndexRoute = AppSimuladosSlugIndexRouteImport.update({
  id: '/simulados/$slug/',
  path: '/simulados/$slug/',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaSlugIndexRoute = AppBibliotecaSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBibliotecaSlugRoute,
} as any)
const AppVadeMecumEstatutosSlugRoute =
  AppVadeMecumEstatutosSlugRouteImport.update({
    id: '/estatutos/$slug',
    path: '/estatutos/$slug',
    getParentRoute: () => AppVadeMecumRoute,
  } as any)
const AppSimuladosSlugPraticarRoute =
  AppSimuladosSlugPraticarRouteImport.update({
    id: '/simulados/$slug/praticar',
    path: '/simulados/$slug/praticar',
    getParentRoute: () => AppRoute,
  } as any)
const AppBibliotecaSlugBookIdRoute = AppBibliotecaSlugBookIdRouteImport.update({
  id: '/$bookId',
  path: '/$bookId',
  getParentRoute: () => AppBibliotecaSlugRoute,
} as any)
const AppBibliotecaSlugBookIdIndexRoute =
  AppBibliotecaSlugBookIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppBibliotecaSlugBookIdRoute,
  } as any)
const AppSimuladosSlugResultadoTentativaIdRoute =
  AppSimuladosSlugResultadoTentativaIdRouteImport.update({
    id: '/simulados/$slug/resultado/$tentativaId',
    path: '/simulados/$slug/resultado/$tentativaId',
    getParentRoute: () => AppRoute,
  } as any)
const AppResumosCapituloLivroIdOrdemRoute =
  AppResumosCapituloLivroIdOrdemRouteImport.update({
    id: '/resumos/capitulo/$livroId/$ordem',
    path: '/resumos/capitulo/$livroId/$ordem',
    getParentRoute: () => AppRoute,
  } as any)
const AppBibliotecaSlugBookIdLerRoute =
  AppBibliotecaSlugBookIdLerRouteImport.update({
    id: '/ler',
    path: '/ler',
    getParentRoute: () => AppBibliotecaSlugBookIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/app': typeof AppAppRoute
  '/assistente': typeof AppAssistenteRoute
  '/audioaulas': typeof AppAudioaulasRoute
  '/aulas': typeof AppAulasRoute
  '/biblioteca': typeof AppBibliotecaRouteWithChildren
  '/blog': typeof AppBlogRouteWithChildren
  '/flashcards': typeof AppFlashcardsRoute
  '/materias': typeof AppMateriasRouteWithChildren
  '/noticias': typeof AppNoticiasRouteWithChildren
  '/perfil': typeof AppPerfilRoute
  '/plano-estudo': typeof AppPlanoEstudoRoute
  '/progresso': typeof AppProgressoRoute
  '/questoes': typeof AppQuestoesRoute
  '/reta-final': typeof AppRetaFinalRoute
  '/vade-mecum': typeof AppVadeMecumRouteWithChildren
  '/admin/blog': typeof AppAdminBlogRoute
  '/admin/resumos': typeof AppAdminResumosRoute
  '/admin/simulados': typeof AppAdminSimuladosRoute
  '/biblioteca/$slug': typeof AppBibliotecaSlugRouteWithChildren
  '/blog/$slug': typeof AppBlogSlugRoute
  '/materias/$slug': typeof AppMateriasSlugRoute
  '/noticias/$id': typeof AppNoticiasIdRoute
  '/oab/caderno-erros': typeof AppOabCadernoErrosRoute
  '/oab/calendario': typeof AppOabCalendarioRoute
  '/oab/cronograma': typeof AppOabCronogramaRoute
  '/oab/o-que-estudar': typeof AppOabOQueEstudarRoute
  '/oab/peca-modelo': typeof AppOabPecaModeloRoute
  '/oab/primeira-fase': typeof AppOabPrimeiraFaseRoute
  '/oab/progresso': typeof AppOabProgressoRoute
  '/oab/reforco': typeof AppOabReforcoRoute
  '/oab/segunda-fase': typeof AppOabSegundaFaseRoute
  '/provas/$numero': typeof AppProvasNumeroRoute
  '/resumos/$livroId': typeof AppResumosLivroIdRoute
  '/api/public/seed-provas': typeof ApiPublicSeedProvasRoute
  '/admin/': typeof AppAdminIndexRoute
  '/biblioteca/': typeof AppBibliotecaIndexRoute
  '/provas/': typeof AppProvasIndexRoute
  '/resumos/': typeof AppResumosIndexRoute
  '/simulados/': typeof AppSimuladosIndexRoute
  '/biblioteca/$slug/$bookId': typeof AppBibliotecaSlugBookIdRouteWithChildren
  '/simulados/$slug/praticar': typeof AppSimuladosSlugPraticarRoute
  '/vade-mecum/estatutos/$slug': typeof AppVadeMecumEstatutosSlugRoute
  '/biblioteca/$slug/': typeof AppBibliotecaSlugIndexRoute
  '/simulados/$slug/': typeof AppSimuladosSlugIndexRoute
  '/vade-mecum/estatutos/': typeof AppVadeMecumEstatutosIndexRoute
  '/biblioteca/$slug/$bookId/ler': typeof AppBibliotecaSlugBookIdLerRoute
  '/resumos/capitulo/$livroId/$ordem': typeof AppResumosCapituloLivroIdOrdemRoute
  '/simulados/$slug/resultado/$tentativaId': typeof AppSimuladosSlugResultadoTentativaIdRoute
  '/biblioteca/$slug/$bookId/': typeof AppBibliotecaSlugBookIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app': typeof AppAppRoute
  '/assistente': typeof AppAssistenteRoute
  '/audioaulas': typeof AppAudioaulasRoute
  '/aulas': typeof AppAulasRoute
  '/blog': typeof AppBlogRouteWithChildren
  '/flashcards': typeof AppFlashcardsRoute
  '/materias': typeof AppMateriasRouteWithChildren
  '/noticias': typeof AppNoticiasRouteWithChildren
  '/perfil': typeof AppPerfilRoute
  '/plano-estudo': typeof AppPlanoEstudoRoute
  '/progresso': typeof AppProgressoRoute
  '/questoes': typeof AppQuestoesRoute
  '/reta-final': typeof AppRetaFinalRoute
  '/vade-mecum': typeof AppVadeMecumRouteWithChildren
  '/admin/blog': typeof AppAdminBlogRoute
  '/admin/resumos': typeof AppAdminResumosRoute
  '/admin/simulados': typeof AppAdminSimuladosRoute
  '/blog/$slug': typeof AppBlogSlugRoute
  '/materias/$slug': typeof AppMateriasSlugRoute
  '/noticias/$id': typeof AppNoticiasIdRoute
  '/oab/caderno-erros': typeof AppOabCadernoErrosRoute
  '/oab/calendario': typeof AppOabCalendarioRoute
  '/oab/cronograma': typeof AppOabCronogramaRoute
  '/oab/o-que-estudar': typeof AppOabOQueEstudarRoute
  '/oab/peca-modelo': typeof AppOabPecaModeloRoute
  '/oab/primeira-fase': typeof AppOabPrimeiraFaseRoute
  '/oab/progresso': typeof AppOabProgressoRoute
  '/oab/reforco': typeof AppOabReforcoRoute
  '/oab/segunda-fase': typeof AppOabSegundaFaseRoute
  '/provas/$numero': typeof AppProvasNumeroRoute
  '/resumos/$livroId': typeof AppResumosLivroIdRoute
  '/api/public/seed-provas': typeof ApiPublicSeedProvasRoute
  '/admin': typeof AppAdminIndexRoute
  '/biblioteca': typeof AppBibliotecaIndexRoute
  '/provas': typeof AppProvasIndexRoute
  '/resumos': typeof AppResumosIndexRoute
  '/simulados': typeof AppSimuladosIndexRoute
  '/simulados/$slug/praticar': typeof AppSimuladosSlugPraticarRoute
  '/vade-mecum/estatutos/$slug': typeof AppVadeMecumEstatutosSlugRoute
  '/biblioteca/$slug': typeof AppBibliotecaSlugIndexRoute
  '/simulados/$slug': typeof AppSimuladosSlugIndexRoute
  '/vade-mecum/estatutos': typeof AppVadeMecumEstatutosIndexRoute
  '/biblioteca/$slug/$bookId/ler': typeof AppBibliotecaSlugBookIdLerRoute
  '/resumos/capitulo/$livroId/$ordem': typeof AppResumosCapituloLivroIdOrdemRoute
  '/simulados/$slug/resultado/$tentativaId': typeof AppSimuladosSlugResultadoTentativaIdRoute
  '/biblioteca/$slug/$bookId': typeof AppBibliotecaSlugBookIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/app': typeof AppAppRoute
  '/_app/assistente': typeof AppAssistenteRoute
  '/_app/audioaulas': typeof AppAudioaulasRoute
  '/_app/aulas': typeof AppAulasRoute
  '/_app/biblioteca': typeof AppBibliotecaRouteWithChildren
  '/_app/blog': typeof AppBlogRouteWithChildren
  '/_app/flashcards': typeof AppFlashcardsRoute
  '/_app/materias': typeof AppMateriasRouteWithChildren
  '/_app/noticias': typeof AppNoticiasRouteWithChildren
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/plano-estudo': typeof AppPlanoEstudoRoute
  '/_app/progresso': typeof AppProgressoRoute
  '/_app/questoes': typeof AppQuestoesRoute
  '/_app/reta-final': typeof AppRetaFinalRoute
  '/_app/vade-mecum': typeof AppVadeMecumRouteWithChildren
  '/_app/admin/blog': typeof AppAdminBlogRoute
  '/_app/admin/resumos': typeof AppAdminResumosRoute
  '/_app/admin/simulados': typeof AppAdminSimuladosRoute
  '/_app/biblioteca/$slug': typeof AppBibliotecaSlugRouteWithChildren
  '/_app/blog/$slug': typeof AppBlogSlugRoute
  '/_app/materias/$slug': typeof AppMateriasSlugRoute
  '/_app/noticias/$id': typeof AppNoticiasIdRoute
  '/_app/oab/caderno-erros': typeof AppOabCadernoErrosRoute
  '/_app/oab/calendario': typeof AppOabCalendarioRoute
  '/_app/oab/cronograma': typeof AppOabCronogramaRoute
  '/_app/oab/o-que-estudar': typeof AppOabOQueEstudarRoute
  '/_app/oab/peca-modelo': typeof AppOabPecaModeloRoute
  '/_app/oab/primeira-fase': typeof AppOabPrimeiraFaseRoute
  '/_app/oab/progresso': typeof AppOabProgressoRoute
  '/_app/oab/reforco': typeof AppOabReforcoRoute
  '/_app/oab/segunda-fase': typeof AppOabSegundaFaseRoute
  '/_app/provas/$numero': typeof AppProvasNumeroRoute
  '/_app/resumos/$livroId': typeof AppResumosLivroIdRoute
  '/api/public/seed-provas': typeof ApiPublicSeedProvasRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/biblioteca/': typeof AppBibliotecaIndexRoute
  '/_app/provas/': typeof AppProvasIndexRoute
  '/_app/resumos/': typeof AppResumosIndexRoute
  '/_app/simulados/': typeof AppSimuladosIndexRoute
  '/_app/biblioteca/$slug/$bookId': typeof AppBibliotecaSlugBookIdRouteWithChildren
  '/_app/simulados/$slug/praticar': typeof AppSimuladosSlugPraticarRoute
  '/_app/vade-mecum/estatutos/$slug': typeof AppVadeMecumEstatutosSlugRoute
  '/_app/biblioteca/$slug/': typeof AppBibliotecaSlugIndexRoute
  '/_app/simulados/$slug/': typeof AppSimuladosSlugIndexRoute
  '/_app/vade-mecum/estatutos/': typeof AppVadeMecumEstatutosIndexRoute
  '/_app/biblioteca/$slug/$bookId/ler': typeof AppBibliotecaSlugBookIdLerRoute
  '/_app/resumos/capitulo/$livroId/$ordem': typeof AppResumosCapituloLivroIdOrdemRoute
  '/_app/simulados/$slug/resultado/$tentativaId': typeof AppSimuladosSlugResultadoTentativaIdRoute
  '/_app/biblioteca/$slug/$bookId/': typeof AppBibliotecaSlugBookIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/app'
    | '/assistente'
    | '/audioaulas'
    | '/aulas'
    | '/biblioteca'
    | '/blog'
    | '/flashcards'
    | '/materias'
    | '/noticias'
    | '/perfil'
    | '/plano-estudo'
    | '/progresso'
    | '/questoes'
    | '/reta-final'
    | '/vade-mecum'
    | '/admin/blog'
    | '/admin/resumos'
    | '/admin/simulados'
    | '/biblioteca/$slug'
    | '/blog/$slug'
    | '/materias/$slug'
    | '/noticias/$id'
    | '/oab/caderno-erros'
    | '/oab/calendario'
    | '/oab/cronograma'
    | '/oab/o-que-estudar'
    | '/oab/peca-modelo'
    | '/oab/primeira-fase'
    | '/oab/progresso'
    | '/oab/reforco'
    | '/oab/segunda-fase'
    | '/provas/$numero'
    | '/resumos/$livroId'
    | '/api/public/seed-provas'
    | '/admin/'
    | '/biblioteca/'
    | '/provas/'
    | '/resumos/'
    | '/simulados/'
    | '/biblioteca/$slug/$bookId'
    | '/simulados/$slug/praticar'
    | '/vade-mecum/estatutos/$slug'
    | '/biblioteca/$slug/'
    | '/simulados/$slug/'
    | '/vade-mecum/estatutos/'
    | '/biblioteca/$slug/$bookId/ler'
    | '/resumos/capitulo/$livroId/$ordem'
    | '/simulados/$slug/resultado/$tentativaId'
    | '/biblioteca/$slug/$bookId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/app'
    | '/assistente'
    | '/audioaulas'
    | '/aulas'
    | '/blog'
    | '/flashcards'
    | '/materias'
    | '/noticias'
    | '/perfil'
    | '/plano-estudo'
    | '/progresso'
    | '/questoes'
    | '/reta-final'
    | '/vade-mecum'
    | '/admin/blog'
    | '/admin/resumos'
    | '/admin/simulados'
    | '/blog/$slug'
    | '/materias/$slug'
    | '/noticias/$id'
    | '/oab/caderno-erros'
    | '/oab/calendario'
    | '/oab/cronograma'
    | '/oab/o-que-estudar'
    | '/oab/peca-modelo'
    | '/oab/primeira-fase'
    | '/oab/progresso'
    | '/oab/reforco'
    | '/oab/segunda-fase'
    | '/provas/$numero'
    | '/resumos/$livroId'
    | '/api/public/seed-provas'
    | '/admin'
    | '/biblioteca'
    | '/provas'
    | '/resumos'
    | '/simulados'
    | '/simulados/$slug/praticar'
    | '/vade-mecum/estatutos/$slug'
    | '/biblioteca/$slug'
    | '/simulados/$slug'
    | '/vade-mecum/estatutos'
    | '/biblioteca/$slug/$bookId/ler'
    | '/resumos/capitulo/$livroId/$ordem'
    | '/simulados/$slug/resultado/$tentativaId'
    | '/biblioteca/$slug/$bookId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/_app/admin'
    | '/_app/app'
    | '/_app/assistente'
    | '/_app/audioaulas'
    | '/_app/aulas'
    | '/_app/biblioteca'
    | '/_app/blog'
    | '/_app/flashcards'
    | '/_app/materias'
    | '/_app/noticias'
    | '/_app/perfil'
    | '/_app/plano-estudo'
    | '/_app/progresso'
    | '/_app/questoes'
    | '/_app/reta-final'
    | '/_app/vade-mecum'
    | '/_app/admin/blog'
    | '/_app/admin/resumos'
    | '/_app/admin/simulados'
    | '/_app/biblioteca/$slug'
    | '/_app/blog/$slug'
    | '/_app/materias/$slug'
    | '/_app/noticias/$id'
    | '/_app/oab/caderno-erros'
    | '/_app/oab/calendario'
    | '/_app/oab/cronograma'
    | '/_app/oab/o-que-estudar'
    | '/_app/oab/peca-modelo'
    | '/_app/oab/primeira-fase'
    | '/_app/oab/progresso'
    | '/_app/oab/reforco'
    | '/_app/oab/segunda-fase'
    | '/_app/provas/$numero'
    | '/_app/resumos/$livroId'
    | '/api/public/seed-provas'
    | '/_app/admin/'
    | '/_app/biblioteca/'
    | '/_app/provas/'
    | '/_app/resumos/'
    | '/_app/simulados/'
    | '/_app/biblioteca/$slug/$bookId'
    | '/_app/simulados/$slug/praticar'
    | '/_app/vade-mecum/estatutos/$slug'
    | '/_app/biblioteca/$slug/'
    | '/_app/simulados/$slug/'
    | '/_app/vade-mecum/estatutos/'
    | '/_app/biblioteca/$slug/$bookId/ler'
    | '/_app/resumos/capitulo/$livroId/$ordem'
    | '/_app/simulados/$slug/resultado/$tentativaId'
    | '/_app/biblioteca/$slug/$bookId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiPublicSeedProvasRoute: typeof ApiPublicSeedProvasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vade-mecum': {
      id: '/_app/vade-mecum'
      path: '/vade-mecum'
      fullPath: '/vade-mecum'
      preLoaderRoute: typeof AppVadeMecumRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reta-final': {
      id: '/_app/reta-final'
      path: '/reta-final'
      fullPath: '/reta-final'
      preLoaderRoute: typeof AppRetaFinalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/questoes': {
      id: '/_app/questoes'
      path: '/questoes'
      fullPath: '/questoes'
      preLoaderRoute: typeof AppQuestoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progresso': {
      id: '/_app/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof AppProgressoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plano-estudo': {
      id: '/_app/plano-estudo'
      path: '/plano-estudo'
      fullPath: '/plano-estudo'
      preLoaderRoute: typeof AppPlanoEstudoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/noticias': {
      id: '/_app/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof AppNoticiasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materias': {
      id: '/_app/materias'
      path: '/materias'
      fullPath: '/materias'
      preLoaderRoute: typeof AppMateriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flashcards': {
      id: '/_app/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AppFlashcardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blog': {
      id: '/_app/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AppBlogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca': {
      id: '/_app/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aulas': {
      id: '/_app/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AppAulasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audioaulas': {
      id: '/_app/audioaulas'
      path: '/audioaulas'
      fullPath: '/audioaulas'
      preLoaderRoute: typeof AppAudioaulasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistente': {
      id: '/_app/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AppAssistenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/simulados/': {
      id: '/_app/simulados/'
      path: '/simulados'
      fullPath: '/simulados/'
      preLoaderRoute: typeof AppSimuladosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumos/': {
      id: '/_app/resumos/'
      path: '/resumos'
      fullPath: '/resumos/'
      preLoaderRoute: typeof AppResumosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/provas/': {
      id: '/_app/provas/'
      path: '/provas'
      fullPath: '/provas/'
      preLoaderRoute: typeof AppProvasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca/': {
      id: '/_app/biblioteca/'
      path: '/'
      fullPath: '/biblioteca/'
      preLoaderRoute: typeof AppBibliotecaIndexRouteImport
      parentRoute: typeof AppBibliotecaRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/public/seed-provas': {
      id: '/api/public/seed-provas'
      path: '/api/public/seed-provas'
      fullPath: '/api/public/seed-provas'
      preLoaderRoute: typeof ApiPublicSeedProvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/resumos/$livroId': {
      id: '/_app/resumos/$livroId'
      path: '/resumos/$livroId'
      fullPath: '/resumos/$livroId'
      preLoaderRoute: typeof AppResumosLivroIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/provas/$numero': {
      id: '/_app/provas/$numero'
      path: '/provas/$numero'
      fullPath: '/provas/$numero'
      preLoaderRoute: typeof AppProvasNumeroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oab/segunda-fase': {
      id: '/_app/oab/segunda-fase'
      path: '/oab/segunda-fase'
      fullPath: '/oab/segunda-fase'
      preLoaderRoute: typeof AppOabSegundaFaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oab/reforco': {
      id: '/_app/oab/reforco'
      path: '/oab/reforco'
      fullPath: '/oab/reforco'
      preLoaderRoute: typeof AppOabReforcoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oab/progresso': {
      id: '/_app/oab/progresso'
      path: '/oab/progresso'
      fullPath: '/oab/progresso'
      preLoaderRoute: typeof AppOabProgressoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oab/primeira-fase': {
      id: '/_app/oab/primeira-fase'
      path: '/oab/primeira-fase'
      fullPath: '/oab/primeira-fase'
      preLoaderRoute: typeof AppOabPrimeiraFaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oab/peca-modelo': {
      id: '/_app/oab/peca-modelo'
      path: '/oab/peca-modelo'
      fullPath: '/oab/peca-modelo'
      preLoaderRoute: typeof AppOabPecaModeloRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oab/o-que-estudar': {
      id: '/_app/oab/o-que-estudar'
      path: '/oab/o-que-estudar'
      fullPath: '/oab/o-que-estudar'
      preLoaderRoute: typeof AppOabOQueEstudarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oab/cronograma': {
      id: '/_app/oab/cronograma'
      path: '/oab/cronograma'
      fullPath: '/oab/cronograma'
      preLoaderRoute: typeof AppOabCronogramaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oab/calendario': {
      id: '/_app/oab/calendario'
      path: '/oab/calendario'
      fullPath: '/oab/calendario'
      preLoaderRoute: typeof AppOabCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oab/caderno-erros': {
      id: '/_app/oab/caderno-erros'
      path: '/oab/caderno-erros'
      fullPath: '/oab/caderno-erros'
      preLoaderRoute: typeof AppOabCadernoErrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/noticias/$id': {
      id: '/_app/noticias/$id'
      path: '/$id'
      fullPath: '/noticias/$id'
      preLoaderRoute: typeof AppNoticiasIdRouteImport
      parentRoute: typeof AppNoticiasRoute
    }
    '/_app/materias/$slug': {
      id: '/_app/materias/$slug'
      path: '/$slug'
      fullPath: '/materias/$slug'
      preLoaderRoute: typeof AppMateriasSlugRouteImport
      parentRoute: typeof AppMateriasRoute
    }
    '/_app/blog/$slug': {
      id: '/_app/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof AppBlogSlugRouteImport
      parentRoute: typeof AppBlogRoute
    }
    '/_app/biblioteca/$slug': {
      id: '/_app/biblioteca/$slug'
      path: '/$slug'
      fullPath: '/biblioteca/$slug'
      preLoaderRoute: typeof AppBibliotecaSlugRouteImport
      parentRoute: typeof AppBibliotecaRoute
    }
    '/_app/admin/simulados': {
      id: '/_app/admin/simulados'
      path: '/simulados'
      fullPath: '/admin/simulados'
      preLoaderRoute: typeof AppAdminSimuladosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/resumos': {
      id: '/_app/admin/resumos'
      path: '/resumos'
      fullPath: '/admin/resumos'
      preLoaderRoute: typeof AppAdminResumosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/blog': {
      id: '/_app/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AppAdminBlogRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/vade-mecum/estatutos/': {
      id: '/_app/vade-mecum/estatutos/'
      path: '/estatutos'
      fullPath: '/vade-mecum/estatutos/'
      preLoaderRoute: typeof AppVadeMecumEstatutosIndexRouteImport
      parentRoute: typeof AppVadeMecumRoute
    }
    '/_app/simulados/$slug/': {
      id: '/_app/simulados/$slug/'
      path: '/simulados/$slug'
      fullPath: '/simulados/$slug/'
      preLoaderRoute: typeof AppSimuladosSlugIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca/$slug/': {
      id: '/_app/biblioteca/$slug/'
      path: '/'
      fullPath: '/biblioteca/$slug/'
      preLoaderRoute: typeof AppBibliotecaSlugIndexRouteImport
      parentRoute: typeof AppBibliotecaSlugRoute
    }
    '/_app/vade-mecum/estatutos/$slug': {
      id: '/_app/vade-mecum/estatutos/$slug'
      path: '/estatutos/$slug'
      fullPath: '/vade-mecum/estatutos/$slug'
      preLoaderRoute: typeof AppVadeMecumEstatutosSlugRouteImport
      parentRoute: typeof AppVadeMecumRoute
    }
    '/_app/simulados/$slug/praticar': {
      id: '/_app/simulados/$slug/praticar'
      path: '/simulados/$slug/praticar'
      fullPath: '/simulados/$slug/praticar'
      preLoaderRoute: typeof AppSimuladosSlugPraticarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca/$slug/$bookId': {
      id: '/_app/biblioteca/$slug/$bookId'
      path: '/$bookId'
      fullPath: '/biblioteca/$slug/$bookId'
      preLoaderRoute: typeof AppBibliotecaSlugBookIdRouteImport
      parentRoute: typeof AppBibliotecaSlugRoute
    }
    '/_app/biblioteca/$slug/$bookId/': {
      id: '/_app/biblioteca/$slug/$bookId/'
      path: '/'
      fullPath: '/biblioteca/$slug/$bookId/'
      preLoaderRoute: typeof AppBibliotecaSlugBookIdIndexRouteImport
      parentRoute: typeof AppBibliotecaSlugBookIdRoute
    }
    '/_app/simulados/$slug/resultado/$tentativaId': {
      id: '/_app/simulados/$slug/resultado/$tentativaId'
      path: '/simulados/$slug/resultado/$tentativaId'
      fullPath: '/simulados/$slug/resultado/$tentativaId'
      preLoaderRoute: typeof AppSimuladosSlugResultadoTentativaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumos/capitulo/$livroId/$ordem': {
      id: '/_app/resumos/capitulo/$livroId/$ordem'
      path: '/resumos/capitulo/$livroId/$ordem'
      fullPath: '/resumos/capitulo/$livroId/$ordem'
      preLoaderRoute: typeof AppResumosCapituloLivroIdOrdemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca/$slug/$bookId/ler': {
      id: '/_app/biblioteca/$slug/$bookId/ler'
      path: '/ler'
      fullPath: '/biblioteca/$slug/$bookId/ler'
      preLoaderRoute: typeof AppBibliotecaSlugBookIdLerRouteImport
      parentRoute: typeof AppBibliotecaSlugBookIdRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminBlogRoute: typeof AppAdminBlogRoute
  AppAdminResumosRoute: typeof AppAdminResumosRoute
  AppAdminSimuladosRoute: typeof AppAdminSimuladosRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminBlogRoute: AppAdminBlogRoute,
  AppAdminResumosRoute: AppAdminResumosRoute,
  AppAdminSimuladosRoute: AppAdminSimuladosRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppBibliotecaSlugBookIdRouteChildren {
  AppBibliotecaSlugBookIdLerRoute: typeof AppBibliotecaSlugBookIdLerRoute
  AppBibliotecaSlugBookIdIndexRoute: typeof AppBibliotecaSlugBookIdIndexRoute
}

const AppBibliotecaSlugBookIdRouteChildren: AppBibliotecaSlugBookIdRouteChildren =
  {
    AppBibliotecaSlugBookIdLerRoute: AppBibliotecaSlugBookIdLerRoute,
    AppBibliotecaSlugBookIdIndexRoute: AppBibliotecaSlugBookIdIndexRoute,
  }

const AppBibliotecaSlugBookIdRouteWithChildren =
  AppBibliotecaSlugBookIdRoute._addFileChildren(
    AppBibliotecaSlugBookIdRouteChildren,
  )

interface AppBibliotecaSlugRouteChildren {
  AppBibliotecaSlugBookIdRoute: typeof AppBibliotecaSlugBookIdRouteWithChildren
  AppBibliotecaSlugIndexRoute: typeof AppBibliotecaSlugIndexRoute
}

const AppBibliotecaSlugRouteChildren: AppBibliotecaSlugRouteChildren = {
  AppBibliotecaSlugBookIdRoute: AppBibliotecaSlugBookIdRouteWithChildren,
  AppBibliotecaSlugIndexRoute: AppBibliotecaSlugIndexRoute,
}

const AppBibliotecaSlugRouteWithChildren =
  AppBibliotecaSlugRoute._addFileChildren(AppBibliotecaSlugRouteChildren)

interface AppBibliotecaRouteChildren {
  AppBibliotecaSlugRoute: typeof AppBibliotecaSlugRouteWithChildren
  AppBibliotecaIndexRoute: typeof AppBibliotecaIndexRoute
}

const AppBibliotecaRouteChildren: AppBibliotecaRouteChildren = {
  AppBibliotecaSlugRoute: AppBibliotecaSlugRouteWithChildren,
  AppBibliotecaIndexRoute: AppBibliotecaIndexRoute,
}

const AppBibliotecaRouteWithChildren = AppBibliotecaRoute._addFileChildren(
  AppBibliotecaRouteChildren,
)

interface AppBlogRouteChildren {
  AppBlogSlugRoute: typeof AppBlogSlugRoute
}

const AppBlogRouteChildren: AppBlogRouteChildren = {
  AppBlogSlugRoute: AppBlogSlugRoute,
}

const AppBlogRouteWithChildren =
  AppBlogRoute._addFileChildren(AppBlogRouteChildren)

interface AppMateriasRouteChildren {
  AppMateriasSlugRoute: typeof AppMateriasSlugRoute
}

const AppMateriasRouteChildren: AppMateriasRouteChildren = {
  AppMateriasSlugRoute: AppMateriasSlugRoute,
}

const AppMateriasRouteWithChildren = AppMateriasRoute._addFileChildren(
  AppMateriasRouteChildren,
)

interface AppNoticiasRouteChildren {
  AppNoticiasIdRoute: typeof AppNoticiasIdRoute
}

const AppNoticiasRouteChildren: AppNoticiasRouteChildren = {
  AppNoticiasIdRoute: AppNoticiasIdRoute,
}

const AppNoticiasRouteWithChildren = AppNoticiasRoute._addFileChildren(
  AppNoticiasRouteChildren,
)

interface AppVadeMecumRouteChildren {
  AppVadeMecumEstatutosSlugRoute: typeof AppVadeMecumEstatutosSlugRoute
  AppVadeMecumEstatutosIndexRoute: typeof AppVadeMecumEstatutosIndexRoute
}

const AppVadeMecumRouteChildren: AppVadeMecumRouteChildren = {
  AppVadeMecumEstatutosSlugRoute: AppVadeMecumEstatutosSlugRoute,
  AppVadeMecumEstatutosIndexRoute: AppVadeMecumEstatutosIndexRoute,
}

const AppVadeMecumRouteWithChildren = AppVadeMecumRoute._addFileChildren(
  AppVadeMecumRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAppRoute: typeof AppAppRoute
  AppAssistenteRoute: typeof AppAssistenteRoute
  AppAudioaulasRoute: typeof AppAudioaulasRoute
  AppAulasRoute: typeof AppAulasRoute
  AppBibliotecaRoute: typeof AppBibliotecaRouteWithChildren
  AppBlogRoute: typeof AppBlogRouteWithChildren
  AppFlashcardsRoute: typeof AppFlashcardsRoute
  AppMateriasRoute: typeof AppMateriasRouteWithChildren
  AppNoticiasRoute: typeof AppNoticiasRouteWithChildren
  AppPerfilRoute: typeof AppPerfilRoute
  AppPlanoEstudoRoute: typeof AppPlanoEstudoRoute
  AppProgressoRoute: typeof AppProgressoRoute
  AppQuestoesRoute: typeof AppQuestoesRoute
  AppRetaFinalRoute: typeof AppRetaFinalRoute
  AppVadeMecumRoute: typeof AppVadeMecumRouteWithChildren
  AppOabCadernoErrosRoute: typeof AppOabCadernoErrosRoute
  AppOabCalendarioRoute: typeof AppOabCalendarioRoute
  AppOabCronogramaRoute: typeof AppOabCronogramaRoute
  AppOabOQueEstudarRoute: typeof AppOabOQueEstudarRoute
  AppOabPecaModeloRoute: typeof AppOabPecaModeloRoute
  AppOabPrimeiraFaseRoute: typeof AppOabPrimeiraFaseRoute
  AppOabProgressoRoute: typeof AppOabProgressoRoute
  AppOabReforcoRoute: typeof AppOabReforcoRoute
  AppOabSegundaFaseRoute: typeof AppOabSegundaFaseRoute
  AppProvasNumeroRoute: typeof AppProvasNumeroRoute
  AppResumosLivroIdRoute: typeof AppResumosLivroIdRoute
  AppProvasIndexRoute: typeof AppProvasIndexRoute
  AppResumosIndexRoute: typeof AppResumosIndexRoute
  AppSimuladosIndexRoute: typeof AppSimuladosIndexRoute
  AppSimuladosSlugPraticarRoute: typeof AppSimuladosSlugPraticarRoute
  AppSimuladosSlugIndexRoute: typeof AppSimuladosSlugIndexRoute
  AppResumosCapituloLivroIdOrdemRoute: typeof AppResumosCapituloLivroIdOrdemRoute
  AppSimuladosSlugResultadoTentativaIdRoute: typeof AppSimuladosSlugResultadoTentativaIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAppRoute: AppAppRoute,
  AppAssistenteRoute: AppAssistenteRoute,
  AppAudioaulasRoute: AppAudioaulasRoute,
  AppAulasRoute: AppAulasRoute,
  AppBibliotecaRoute: AppBibliotecaRouteWithChildren,
  AppBlogRoute: AppBlogRouteWithChildren,
  AppFlashcardsRoute: AppFlashcardsRoute,
  AppMateriasRoute: AppMateriasRouteWithChildren,
  AppNoticiasRoute: AppNoticiasRouteWithChildren,
  AppPerfilRoute: AppPerfilRoute,
  AppPlanoEstudoRoute: AppPlanoEstudoRoute,
  AppProgressoRoute: AppProgressoRoute,
  AppQuestoesRoute: AppQuestoesRoute,
  AppRetaFinalRoute: AppRetaFinalRoute,
  AppVadeMecumRoute: AppVadeMecumRouteWithChildren,
  AppOabCadernoErrosRoute: AppOabCadernoErrosRoute,
  AppOabCalendarioRoute: AppOabCalendarioRoute,
  AppOabCronogramaRoute: AppOabCronogramaRoute,
  AppOabOQueEstudarRoute: AppOabOQueEstudarRoute,
  AppOabPecaModeloRoute: AppOabPecaModeloRoute,
  AppOabPrimeiraFaseRoute: AppOabPrimeiraFaseRoute,
  AppOabProgressoRoute: AppOabProgressoRoute,
  AppOabReforcoRoute: AppOabReforcoRoute,
  AppOabSegundaFaseRoute: AppOabSegundaFaseRoute,
  AppProvasNumeroRoute: AppProvasNumeroRoute,
  AppResumosLivroIdRoute: AppResumosLivroIdRoute,
  AppProvasIndexRoute: AppProvasIndexRoute,
  AppResumosIndexRoute: AppResumosIndexRoute,
  AppSimuladosIndexRoute: AppSimuladosIndexRoute,
  AppSimuladosSlugPraticarRoute: AppSimuladosSlugPraticarRoute,
  AppSimuladosSlugIndexRoute: AppSimuladosSlugIndexRoute,
  AppResumosCapituloLivroIdOrdemRoute: AppResumosCapituloLivroIdOrdemRoute,
  AppSimuladosSlugResultadoTentativaIdRoute:
    AppSimuladosSlugResultadoTentativaIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiPublicSeedProvasRoute: ApiPublicSeedProvasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
