-- Prepend epígrafes (rubricas) do CP a artigos cujo texto começa direto com 'Art.'
-- Fonte: Planalto (DL 2.848/1940 compilado).

UPDATE vade_mecum_artigos SET texto = 'Anterioridade da Lei' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '1' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Exclusão de ilicitude' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '23' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Duração das penas restritivas de direitos' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '55' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Pena de interdição' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '56' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Pena de interdição' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '57' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Reincidência' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '64' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Atenuante inominada' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '66' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Condições' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '79' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Estatuição' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '80' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Efeitos da revogação' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '88' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Extinção' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '90' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Confisco alargado' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '91-A' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Outros efeitos' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '92' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Reabilitação' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '94' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Revogação da reabilitação' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '95' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Perdão do ofendido' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '106' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Punibilidade de crime que é pressuposto' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '108' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Prescrição das penas mais leves' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '118' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Prescrição no concurso de crimes' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '119' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Feminicídio' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '121-A' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Forma qualificada' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '127' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Aborto necessário' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '128' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Condicionamento de atendimento médico-hospitalar emergencial' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '135-A' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Pedido de explicações em juízo' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '144' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Disposições comuns' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '145' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Violência psicológica contra a mulher' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '147-B' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Ação penal' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '154-B' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Supressão ou alteração de marca em animais' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '162' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Disposições gerais' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '170' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Fraude com utilização de ativos virtuais, valores mobiliários ou ativos financeiros' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '171-A' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Outras fraudes' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '174' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Ação penal' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '182' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Disposições gerais' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '183' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Disposições gerais' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '183-A' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Procedimento' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '186' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Concorrência desleal' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '195' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Estupro' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '213' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Atentado violento ao pudor' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '214' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Atentado ao pudor mediante fraude' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '216' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Assédio sexual' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '216-A' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Tráfico interno de pessoa para fim de exploração sexual' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '231-A' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Promoção ou facilitação' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '232' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Permissão a menor' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '247' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Perigo de desastre ferroviário' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '260' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Interrupção ou perturbação de serviço telegráfico, telefônico, informático, telemático ou de informação de utilidade pública' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '266' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Comércio, posse ou uso de entorpecente' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '281' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Associação Criminosa' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '288' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Constituição de milícia privada' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '288-A' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Falsificação de documento particular' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '298' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Falsa identidade' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '310' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Fraudes em certames de interesse público' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '311-A' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Vedação ao acesso a aparelho telefônico em estabelecimento prisional' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '319-A' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Contrabando' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '334-A' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Sonegação de contribuição previdenciária' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '337-A' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Disposições comuns' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '337-P' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Corrupção ativa de testemunha ou perito' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '343' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Ingresso de aparelho telefônico em estabelecimento prisional' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '349-A' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Negociação prejudicial com nação estrangeira' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '359-I' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Atentado à soberania' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '359-J' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Espionagem' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '359-K' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Abolição violenta do Estado Democrático de Direito' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '359-L' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Golpe de Estado' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '359-M' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Interrupção do processo eleitoral' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '359-N' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Violência política' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '359-O' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Sabotagem' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '359-P' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Sabotagem' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '359-Q' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Sabotagem' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '359-R' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Disposições comuns' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '359-T' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Disposições comuns' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '359-U' AND texto ~* '^\s*art\.';
UPDATE vade_mecum_artigos SET texto = 'Vigência' || E'\n\n' || texto WHERE lei_id = (SELECT id FROM vade_mecum_leis WHERE slug='cp') AND numero = '361' AND texto ~* '^\s*art\.';