
-- BIBLIOTECA-CLASSICOS
CREATE TABLE public."BIBLIOTECA-CLASSICOS" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area TEXT,
  livro TEXT,
  autor TEXT,
  link TEXT,
  imagem TEXT,
  sobre TEXT,
  beneficios TEXT,
  download TEXT,
  "Capa-area" TEXT,
  aula TEXT,
  resumo_capitulos JSONB,
  questoes_resumo JSONB,
  resumo_gerado_em TIMESTAMPTZ,
  capitulos_gerados INTEGER,
  total_capitulos INTEGER,
  analise_status TEXT,
  total_paginas INTEGER,
  total_temas INTEGER,
  url_videoaula TEXT
);
ALTER TABLE public."BIBLIOTECA-CLASSICOS" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Leitura pública" ON public."BIBLIOTECA-CLASSICOS" FOR SELECT USING (true);

-- BIBLIOTECA-ESTUDOS
CREATE TABLE public."BIBLIOTECA-ESTUDOS" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Área" TEXT,
  "Ordem" INTEGER,
  "Tema" TEXT,
  "Download" TEXT,
  "Link" TEXT,
  "Capa-area" TEXT,
  "Capa-livro" TEXT,
  "Sobre" TEXT,
  aula TEXT,
  url_capa_gerada TEXT
);
ALTER TABLE public."BIBLIOTECA-ESTUDOS" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Leitura pública" ON public."BIBLIOTECA-ESTUDOS" FOR SELECT USING (true);

-- BIBLIOTECA-ORATORIA
CREATE TABLE public."BIBLIOTECA-ORATORIA" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area TEXT,
  livro TEXT,
  autor TEXT,
  link TEXT,
  imagem TEXT,
  sobre TEXT,
  beneficios TEXT,
  download TEXT,
  "Capa-area" TEXT,
  aula TEXT,
  resumo_capitulos JSONB,
  questoes_resumo JSONB,
  resumo_gerado_em TIMESTAMPTZ
);
ALTER TABLE public."BIBLIOTECA-ORATORIA" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Leitura pública" ON public."BIBLIOTECA-ORATORIA" FOR SELECT USING (true);

-- BIBLIOTECA-LIDERANÇA
CREATE TABLE public."BIBLIOTECA-LIDERANÇA" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area TEXT,
  livro TEXT,
  autor TEXT,
  link TEXT,
  imagem TEXT,
  sobre TEXT,
  beneficios TEXT,
  download TEXT,
  "Capa-area" TEXT,
  aula TEXT,
  resumo_capitulos JSONB,
  questoes_resumo JSONB,
  resumo_gerado_em TIMESTAMPTZ
);
ALTER TABLE public."BIBLIOTECA-LIDERANÇA" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Leitura pública" ON public."BIBLIOTECA-LIDERANÇA" FOR SELECT USING (true);

-- BIBLIOTECA-POLITICA
CREATE TABLE public."BIBLIOTECA-POLITICA" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area TEXT,
  livro TEXT,
  autor TEXT,
  link TEXT,
  imagem TEXT,
  sobre TEXT,
  beneficios TEXT,
  download TEXT,
  "Capa-area" TEXT,
  aula TEXT,
  resumo_capitulos JSONB,
  questoes_resumo JSONB,
  resumo_gerado_em TIMESTAMPTZ,
  capitulos_gerados INTEGER,
  total_capitulos INTEGER
);
ALTER TABLE public."BIBLIOTECA-POLITICA" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Leitura pública" ON public."BIBLIOTECA-POLITICA" FOR SELECT USING (true);

-- BIBLIOTECA-FORA-DA-TOGA
CREATE TABLE public."BIBLIOTECA-FORA-DA-TOGA" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area TEXT,
  livro TEXT,
  autor TEXT,
  link TEXT,
  "capa-livro" TEXT,
  sobre TEXT,
  download TEXT,
  "capa-area" TEXT,
  aula TEXT
);
ALTER TABLE public."BIBLIOTECA-FORA-DA-TOGA" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Leitura pública" ON public."BIBLIOTECA-FORA-DA-TOGA" FOR SELECT USING (true);
