
DROP POLICY IF EXISTS "tmp_import_insert" ON "BIBLIOTECA-CLASSICOS";
DROP POLICY IF EXISTS "tmp_import_insert" ON "BIBLIOTECA-ESTUDOS";
DROP POLICY IF EXISTS "tmp_import_insert" ON "BIBLIOTECA-LIDERANÇA";
DROP POLICY IF EXISTS "tmp_import_insert" ON "BIBLIOTECA-POLITICA";
DROP POLICY IF EXISTS "tmp_import_insert" ON "BIBLIOTECA-FORA-DA-TOGA";
