
CREATE POLICY "tmp_import_insert" ON "BIBLIOTECA-CLASSICOS" FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "tmp_import_insert" ON "BIBLIOTECA-ESTUDOS" FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "tmp_import_insert" ON "BIBLIOTECA-LIDERANÇA" FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "tmp_import_insert" ON "BIBLIOTECA-POLITICA" FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "tmp_import_insert" ON "BIBLIOTECA-FORA-DA-TOGA" FOR INSERT TO anon WITH CHECK (true);
