
CREATE TABLE public.provas_oab (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero INTEGER NOT NULL UNIQUE,
  titulo TEXT NOT NULL,
  ano INTEGER,
  oab_exame_id TEXT,
  oab_source_url TEXT,
  edital_url TEXT,
  prova_1fase_url TEXT,
  gabarito_1fase_url TEXT,
  provas_2fase JSONB NOT NULL DEFAULT '[]'::jsonb,
  outros_arquivos JSONB NOT NULL DEFAULT '[]'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.provas_oab ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Leitura pública provas_oab"
ON public.provas_oab FOR SELECT
USING (true);

CREATE INDEX idx_provas_oab_numero ON public.provas_oab(numero DESC);
