// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajbzwnzbuukwjaydfqui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqYnp3bnpidXVrd2pheWRmcXVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg4OTQxMzIsImV4cCI6MjA5NDQ3MDEzMn0.0_HNBEwCOhqNSoTmrs7NwYWKUJESPFuFNAtzsxQVE5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});