// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(
      ", ",
    )}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

// Lazy singleton — instancia só na primeira chamada e reusa.
let _client: ReturnType<typeof createSupabaseClient> | undefined;
function getClient() {
  if (!_client) _client = createSupabaseClient();
  return _client;
}

// API estável: `import { supabase } from "@/integrations/supabase/client"`.
// Em vez do Proxy quente (custo em cada acesso), expomos getters por
// propriedade. Isso mantém a mesma ergonomia (`supabase.from(...)`, etc.)
// com a vantagem de o cliente real ser criado uma única vez sob demanda.
export const supabase = {
  get auth() {
    return getClient().auth;
  },
  get storage() {
    return getClient().storage;
  },
  get realtime() {
    return getClient().realtime;
  },
  get functions() {
    return getClient().functions;
  },
  from(...args: Parameters<ReturnType<typeof createSupabaseClient>["from"]>) {
    return getClient().from(...args);
  },
  rpc(...args: Parameters<ReturnType<typeof createSupabaseClient>["rpc"]>) {
    return getClient().rpc(...args);
  },
  channel(
    ...args: Parameters<ReturnType<typeof createSupabaseClient>["channel"]>
  ) {
    return getClient().channel(...args);
  },
  removeChannel(
    ...args: Parameters<
      ReturnType<typeof createSupabaseClient>["removeChannel"]
    >
  ) {
    return getClient().removeChannel(...args);
  },
} as unknown as ReturnType<typeof createSupabaseClient>;
